### ISSUE TITLE
Application hangs on macOS High Sierra

### ISSUE THREAD

**Issue by vikman90** [packagesdev/packages#7] opened 2017-09-17 16:38 UTC
Hi,

I'm having issues when compiling a package on High Sierra:

1. I can't open a package using the UI, just when I open it the program hangs, it responds nothing.
2. If I create a new project, it hangs just after entering the new package name.
3. If I try to compile a package using a terminal, I get this error:

```
$ packagesbuild agent.pkgproj
==============================================================================
ERROR:

Description:

goldin_64 returned error code '254'
Step:

Project > Distribution > Package 'agent' > Payload > Split Forks

Description:

Not enough memory to perform operation.
Step:

Project > Distribution > Package 'agent' > Payload > Split Forks
```

On the other hand, I can compile the same package on macOS Sierra with no problems.

This problem persists although I uninstalled the app (using `uninstall.sh`) and reinstalled it again.

Thanks in advance.
Best regards.

**Comment by packagesdev** [comment] 2017-09-17 22:22
1. Known issue.
2. Related to 1.
3. This is a different known issue related to APFS volume.

Mail me at dev.packages@gmail.com if you want to try the latest build of Packages 1.2 that solves these 2 issues.

**Comment by vikman90** [comment] 2017-09-17 22:32
Thank you very much for the prompt response!

**Comment by vikman90** [comment] 2017-09-19 11:45
Hi,

I have upgraded to Packages 1.2 and these problems didn't occur anymore as you said.

But I'm still not able to build the package, this new error appeared in the UI:

![fail](https://user-images.githubusercontent.com/10536251/30590767-57f35d68-9d40-11e7-8444-e8988aeaaee6.png)

If I run the command `packagesbuild` I get this error instead:

```
$ packagesbuild agent.pkgproj
==============================================================================
ERROR:

Description:

Unable to set attributes of item at path "/private/tmp/iJGSOYQm/501/agent/etc"
Step:

Project > Distribution > Package 'agent' > Payload > Assemble

==============================================================================
Build Failed
```

Is this also a known issue?

Thank you again.
Best regards.

**Comment by packagesdev** [comment] 2017-09-25 21:34
Not a known issue in both cases (no explanation in the Build Window and set attributes error).

The issue in the Build window has been fixed in the latest build.

I've added a debug log for this error so the explanation provided by the NSFileManager API should be visible in system.log.

Is etc in your project the real /etc folder (which is a symbolic link)? This could be the explanation.

**Comment by packagesdev** [comment] 2017-09-26 18:38
I'm able to reproduce a problem with adding /etc. So I should be able to fix this quickly.

**Comment by packagesdev** [comment] 2017-09-26 22:59
Problem solved as far as I can tell in the latest builds.

**Comment by Naesstrom** [comment] 2017-10-04 05:37
Any idea when the new 1.2 build will be available that fixes this issue?

**Comment by ferben** [comment] 2017-10-04 06:25
Beta is temporary [here]( http://s.sudre.free.fr/Software/Packages/Q&A_6.html).

**Comment by packagesdev** [comment] 2017-10-08 19:27
Version 1.2 is now available (build 211). http://s.sudre.free.fr/Software/Packages/release_notes.html

**Comment by packagesdev** [comment] 2017-10-10 21:24
There is still a remaining issue when trying to build a package with the /etc symbolic link at the root of the payload. I'm not 100% sure the problem is in my code as this works fine with other symbolic links. Moving to NSFileManager API seems to address the problem but before I can confirm this is the solution, I have to make regression tests regarding resources forks, big files hierarchy, etc.

**Comment by packagesdev** [comment] 2017-10-12 19:57
Problem fixed for 1.2.1.

**Closed** 2017-10-17 23:01 UTC

**Comment by built2order** [comment] 2018-10-28 11:31
I've just experienced this issue using **1.2.4** using **High Sierra 10.13.6**.

```
$ /usr/local/bin/packagesbuild --package-version "2.2" mypackage.pkgproj
==============================================================================
ERROR:

Description:

goldin returned error code (254): "/private/tmp/TK2ti8gE/502/mypackage" is not on an hfs disk
 
Step:

Project > Package > Package "mypackage" > Payload > Split Forks

==============================================================================
Build Failed
```

**Comment by packagesdev** [comment] 2018-10-31 22:56
It looks like that you do not have the latest version of goldin installed on this Mac (i.e. the version installed by version 1.2.4 of Packages)  as this error string does not exist anymore and is replaced by:

"/the/path/" is neither on an hfs nor an apfs disk
