### ISSUE TITLE
macOS 11.0 Big Sur: Hang while remove installer plugin 

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#81] opened 2020-11-26 09:56 UTC
**Reproduce**
Open any project which contain installer plugin, switch to Presentation tab.
Try to remove plugin ⇒ click on "-" icon at bottom "Plugins" area.

**Current state**
App hang ⇒ you have to do force quit.
<img width="1205" alt="Snímek obrazovky 2020-11-26 v 10 48 29" src="https://user-images.githubusercontent.com/45659268/100335527-62611080-2fd5-11eb-8238-38d3e3e0dcb9.png">

**Expected state**
No hang.

**Additional info**
This modal dialogs are reworked completelly so there might be bug in macOS 11.0 and not in Packages.app.

**Workaround**
Edit *.pkgproj in raw text and remove plugin <dict></dict> part manually.

**Comment by packagesdev** [comment] 2020-12-10 21:50
Interesting. I will check this when possible.

**Comment by ferben** [comment] 2020-12-14 20:32
Appear in macOS 11.1 (Big Sur) too.

**Comment by packagesdev** [comment] 2021-01-04 20:13
As far as I can tell, this seems to be caused by a change in AppKit on Big Sur related to the time the - [NSView resetCursorRects]; methods is called.

I have a possible fix for this. I need to check it does not introduce regressions on macOS 10.15 and earlier.

**Comment by stang2019** [comment] 2021-02-08 20:40
Did you guys fix it yet?

**Comment by packagesdev** [comment] 2021-03-06 09:57
Yes, it's fixed but the minor update of the product has not been shipped yet.

**Comment by packagesdev** [comment] 2022-02-05 23:01
Fixed in upcoming 1.2.10 release.

**Closed by packagesdev** 2022-02-05 23:01 UTC
