### ISSUE TITLE
Stuck on "separation des forks"

### ISSUE THREAD

**Issue by pouledodue** [packagesdev/packages#57] opened 2019-10-31 00:59 UTC
Stuck on this:

![Capture d’écran, le 2019-10-30 à 20 58 08](https://user-images.githubusercontent.com/745437/67910202-2d775580-fb58-11e9-8aa7-240ce1ef308f.png)

**Comment by ferben** [comment] 2019-12-09 12:14
Hello,
I have similar issue but not stuck, but error:

> ERROR:
> Description:
> goldin returned error code (255): An error occurred while reading the "com.apple.cs.CodeSignature" attribute (34)
> Step:
> Project > Distribution > Package 'MyApp.app' > Payload > Split Forks
> Build Failed

When I uncheck "Preserve extended attributes" and leave only "Split forks if needed" checked, problem disappear.

Have you checked "Preserve extended attributes" or not?

**Comment by packagesdev** [comment] 2019-12-13 23:08
Can you send the .app bundle exhibiting the issue so that I can try to reproduce (and hopefully fix) the issue?

-> dev.packages@gmail.com

**Comment by packagesdev** [comment] 2019-12-22 22:23
I think I have found the origin of the issue. So no need to provide the .app bundle. This should be addressed in the next minor update.

**Comment by ferben** [comment] 2019-12-22 23:16
Hello,
I made simple installer with simple app.
So if I:
1) Check "Split forks if needed" and "Preserve extended attributes" I get an error as you can see in screenshot
2) Check "Split forks if needed" installer is ok, but installed applications has codesign issue as you can see in text output (SignVerificationOfInstalledApp
[PackagesIssue.zip](https://github.com/packagesdev/packages/files/3993106/PackagesIssue.zip)
.txt)

I wrote #62 because I cannot install my app due this error, so #62 could be "duplicate".

**Comment by packagesdev** [comment] 2019-12-24 11:59
You can find an early version of Packages 1.2.8 at the following URL which should address the issue.

https://drive.google.com/open?id=0B_2n1wyuWXGVVXNPTUlJVnprSGM

**Comment by packagesdev** [comment] 2020-01-09 23:33
Fixed in version 1.2.8

**Closed by packagesdev** 2020-01-09 23:33 UTC
